Set-StrictMode -Version Latest

# FOREGROUND COLOR FUNCTION SHORTHANDS
Function fIndianRed { Format-ConsoleColor24 -Color $PSRainbowColors.IndianRed -Type Fg }
Function fCrimson { Format-ConsoleColor24 -Color $PSRainbowColors.Crimson -Type Fg }
Function fLightCoral { Format-ConsoleColor24 -Color $PSRainbowColors.LightCoral -Type Fg }
Function fRed { Format-ConsoleColor24 -Color $PSRainbowColors.Red -Type Fg }
Function fSalmon { Format-ConsoleColor24 -Color $PSRainbowColors.Salmon -Type Fg }
Function fFireBrick { Format-ConsoleColor24 -Color $PSRainbowColors.FireBrick -Type Fg }
Function fDarkSalmon { Format-ConsoleColor24 -Color $PSRainbowColors.DarkSalmon -Type Fg }
Function fDarkRed { Format-ConsoleColor24 -Color $PSRainbowColors.DarkRed -Type Fg }
Function fPink { Format-ConsoleColor24 -Color $PSRainbowColors.Pink -Type Fg }
Function fMediumVioletRed { Format-ConsoleColor24 -Color $PSRainbowColors.MediumVioletRed -Type Fg }
Function fLightPink { Format-ConsoleColor24 -Color $PSRainbowColors.LightPink -Type Fg }
Function fPaleVioletRed { Format-ConsoleColor24 -Color $PSRainbowColors.PaleVioletRed -Type Fg }
Function fHotPink { Format-ConsoleColor24 -Color $PSRainbowColors.HotPink -Type Fg }
Function fDeepPink { Format-ConsoleColor24 -Color $PSRainbowColors.DeepPink -Type Fg }
Function fLightSalmon { Format-ConsoleColor24 -Color $PSRainbowColors.LightSalmon -Type Fg }
Function fDarkOrange { Format-ConsoleColor24 -Color $PSRainbowColors.DarkOrange -Type Fg }
Function fCoral { Format-ConsoleColor24 -Color $PSRainbowColors.Coral -Type Fg }
Function fOrange { Format-ConsoleColor24 -Color $PSRainbowColors.Orange -Type Fg }
Function fTomato { Format-ConsoleColor24 -Color $PSRainbowColors.Tomato -Type Fg }
Function fGold { Format-ConsoleColor24 -Color $PSRainbowColors.Gold -Type Fg }
Function fOrangeRed { Format-ConsoleColor24 -Color $PSRainbowColors.OrangeRed -Type Fg }
Function fYellow { Format-ConsoleColor24 -Color $PSRainbowColors.Yellow -Type Fg }
Function fLightYellow { Format-ConsoleColor24 -Color $PSRainbowColors.LightYellow -Type Fg }
Function fPapayaWhip { Format-ConsoleColor24 -Color $PSRainbowColors.PapayaWhip -Type Fg }
Function fLemonChiffon { Format-ConsoleColor24 -Color $PSRainbowColors.LemonChiffon -Type Fg }
Function fMoccasin { Format-ConsoleColor24 -Color $PSRainbowColors.Moccasin -Type Fg }
Function fLightGoldenrodYellow { Format-ConsoleColor24 -Color $PSRainbowColors.LightGoldenrodYellow -Type Fg }
Function fPeachPuff { Format-ConsoleColor24 -Color $PSRainbowColors.PeachPuff -Type Fg }
Function fPaleGoldenrod { Format-ConsoleColor24 -Color $PSRainbowColors.PaleGoldenrod -Type Fg }
Function fKhaki { Format-ConsoleColor24 -Color $PSRainbowColors.Khaki -Type Fg }
Function fDarkKhaki { Format-ConsoleColor24 -Color $PSRainbowColors.DarkKhaki -Type Fg }
Function fLavender { Format-ConsoleColor24 -Color $PSRainbowColors.Lavender -Type Fg }
Function fMediumOrchid { Format-ConsoleColor24 -Color $PSRainbowColors.MediumOrchid -Type Fg }
Function fThistle { Format-ConsoleColor24 -Color $PSRainbowColors.Thistle -Type Fg }
Function fDarkOrchid { Format-ConsoleColor24 -Color $PSRainbowColors.DarkOrchid -Type Fg }
Function fPlum { Format-ConsoleColor24 -Color $PSRainbowColors.Plum -Type Fg }
Function fDarkViolet { Format-ConsoleColor24 -Color $PSRainbowColors.DarkViolet -Type Fg }
Function fViolet { Format-ConsoleColor24 -Color $PSRainbowColors.Violet -Type Fg }
Function fBlueViolet { Format-ConsoleColor24 -Color $PSRainbowColors.BlueViolet -Type Fg }
Function fOrchid { Format-ConsoleColor24 -Color $PSRainbowColors.Orchid -Type Fg }
Function fMediumPurple { Format-ConsoleColor24 -Color $PSRainbowColors.MediumPurple -Type Fg }
Function fMagenta { Format-ConsoleColor24 -Color $PSRainbowColors.Magenta -Type Fg }
Function fFuchsia { Format-ConsoleColor24 -Color $PSRainbowColors.Fuchsia -Type Fg }
Function fSlateBlue { Format-ConsoleColor24 -Color $PSRainbowColors.SlateBlue -Type Fg }
Function fMediumSlateBlue { Format-ConsoleColor24 -Color $PSRainbowColors.MediumSlateBlue -Type Fg }
Function fDarkSlateBlue { Format-ConsoleColor24 -Color $PSRainbowColors.DarkSlateBlue -Type Fg }
Function fPurple { Format-ConsoleColor24 -Color $PSRainbowColors.Purple -Type Fg }
Function fIndigo { Format-ConsoleColor24 -Color $PSRainbowColors.Indigo -Type Fg }
Function fGreenYellow { Format-ConsoleColor24 -Color $PSRainbowColors.GreenYellow -Type Fg }
Function fSeaGreen { Format-ConsoleColor24 -Color $PSRainbowColors.SeaGreen -Type Fg }
Function fChartreuse { Format-ConsoleColor24 -Color $PSRainbowColors.Chartreuse -Type Fg }
Function fForestGreen { Format-ConsoleColor24 -Color $PSRainbowColors.ForestGreen -Type Fg }
Function fLawnGreen { Format-ConsoleColor24 -Color $PSRainbowColors.LawnGreen -Type Fg }
Function fGreen { Format-ConsoleColor24 -Color $PSRainbowColors.Green -Type Fg }
Function fLime { Format-ConsoleColor24 -Color $PSRainbowColors.Lime -Type Fg }
Function fDarkGreen { Format-ConsoleColor24 -Color $PSRainbowColors.DarkGreen -Type Fg }
Function fLimeGreen { Format-ConsoleColor24 -Color $PSRainbowColors.LimeGreen -Type Fg }
Function fYellowGreen { Format-ConsoleColor24 -Color $PSRainbowColors.YellowGreen -Type Fg }
Function fPaleGreen { Format-ConsoleColor24 -Color $PSRainbowColors.PaleGreen -Type Fg }
Function fOliveDrab { Format-ConsoleColor24 -Color $PSRainbowColors.OliveDrab -Type Fg }
Function fLightGreen { Format-ConsoleColor24 -Color $PSRainbowColors.LightGreen -Type Fg }
Function fOlive { Format-ConsoleColor24 -Color $PSRainbowColors.Olive -Type Fg }
Function fMediumSpringGreen { Format-ConsoleColor24 -Color $PSRainbowColors.MediumSpringGreen -Type Fg }
Function fDarkOliveGreen { Format-ConsoleColor24 -Color $PSRainbowColors.DarkOliveGreen -Type Fg }
Function fSpringGreen { Format-ConsoleColor24 -Color $PSRainbowColors.SpringGreen -Type Fg }
Function fMediumAquamarine { Format-ConsoleColor24 -Color $PSRainbowColors.MediumAquamarine -Type Fg }
Function fMediumSeaGreen { Format-ConsoleColor24 -Color $PSRainbowColors.MediumSeaGreen -Type Fg }
Function fDarkSeaGreen { Format-ConsoleColor24 -Color $PSRainbowColors.DarkSeaGreen -Type Fg }
Function fLightSeaGreen { Format-ConsoleColor24 -Color $PSRainbowColors.LightSeaGreen -Type Fg }
Function fDarkCyan { Format-ConsoleColor24 -Color $PSRainbowColors.DarkCyan -Type Fg }
Function fTeal { Format-ConsoleColor24 -Color $PSRainbowColors.Teal -Type Fg }
Function fAqua { Format-ConsoleColor24 -Color $PSRainbowColors.Aqua -Type Fg }
Function fCyan { Format-ConsoleColor24 -Color $PSRainbowColors.Cyan -Type Fg }
Function fSkyBlue { Format-ConsoleColor24 -Color $PSRainbowColors.SkyBlue -Type Fg }
Function fLightCyan { Format-ConsoleColor24 -Color $PSRainbowColors.LightCyan -Type Fg }
Function fLightSkyBlue { Format-ConsoleColor24 -Color $PSRainbowColors.LightSkyBlue -Type Fg }
Function fPaleTurquoise { Format-ConsoleColor24 -Color $PSRainbowColors.PaleTurquoise -Type Fg }
Function fDeepSkyBlue { Format-ConsoleColor24 -Color $PSRainbowColors.DeepSkyBlue -Type Fg }
Function fAquamarine { Format-ConsoleColor24 -Color $PSRainbowColors.Aquamarine -Type Fg }
Function fDodgerBlue { Format-ConsoleColor24 -Color $PSRainbowColors.DodgerBlue -Type Fg }
Function fTurquoise { Format-ConsoleColor24 -Color $PSRainbowColors.Turquoise -Type Fg }
Function fCornflowerBlue { Format-ConsoleColor24 -Color $PSRainbowColors.CornflowerBlue -Type Fg }
Function fMediumTurquoise { Format-ConsoleColor24 -Color $PSRainbowColors.MediumTurquoise -Type Fg }
Function fRoyalBlue { Format-ConsoleColor24 -Color $PSRainbowColors.RoyalBlue -Type Fg }
Function fDarkTurquoise { Format-ConsoleColor24 -Color $PSRainbowColors.DarkTurquoise -Type Fg }
Function fBlue { Format-ConsoleColor24 -Color $PSRainbowColors.Blue -Type Fg }
Function fCadetBlue { Format-ConsoleColor24 -Color $PSRainbowColors.CadetBlue -Type Fg }
Function fMediumBlue { Format-ConsoleColor24 -Color $PSRainbowColors.MediumBlue -Type Fg }
Function fSteelBlue { Format-ConsoleColor24 -Color $PSRainbowColors.SteelBlue -Type Fg }
Function fDarkBlue { Format-ConsoleColor24 -Color $PSRainbowColors.DarkBlue -Type Fg }
Function fLightSteelBlue { Format-ConsoleColor24 -Color $PSRainbowColors.LightSteelBlue -Type Fg }
Function fNavy { Format-ConsoleColor24 -Color $PSRainbowColors.Navy -Type Fg }
Function fPowderBlue { Format-ConsoleColor24 -Color $PSRainbowColors.PowderBlue -Type Fg }
Function fMidnightBlue { Format-ConsoleColor24 -Color $PSRainbowColors.MidnightBlue -Type Fg }
Function fLightBlue { Format-ConsoleColor24 -Color $PSRainbowColors.LightBlue -Type Fg }
Function fCornsilk { Format-ConsoleColor24 -Color $PSRainbowColors.Cornsilk -Type Fg }
Function fRosyBrown { Format-ConsoleColor24 -Color $PSRainbowColors.RosyBrown -Type Fg }
Function fBlanchedAlmond { Format-ConsoleColor24 -Color $PSRainbowColors.BlanchedAlmond -Type Fg }
Function fSandyBrown { Format-ConsoleColor24 -Color $PSRainbowColors.SandyBrown -Type Fg }
Function fBisque { Format-ConsoleColor24 -Color $PSRainbowColors.Bisque -Type Fg }
Function fGoldenrod { Format-ConsoleColor24 -Color $PSRainbowColors.Goldenrod -Type Fg }
Function fNavajoWhite { Format-ConsoleColor24 -Color $PSRainbowColors.NavajoWhite -Type Fg }
Function fDarkGoldenrod { Format-ConsoleColor24 -Color $PSRainbowColors.DarkGoldenrod -Type Fg }
Function fWheat { Format-ConsoleColor24 -Color $PSRainbowColors.Wheat -Type Fg }
Function fPeru { Format-ConsoleColor24 -Color $PSRainbowColors.Peru -Type Fg }
Function fBurlyWood { Format-ConsoleColor24 -Color $PSRainbowColors.BurlyWood -Type Fg }
Function fChocolate { Format-ConsoleColor24 -Color $PSRainbowColors.Chocolate -Type Fg }
Function fTan { Format-ConsoleColor24 -Color $PSRainbowColors.Tan -Type Fg }
Function fSaddleBrown { Format-ConsoleColor24 -Color $PSRainbowColors.SaddleBrown -Type Fg }
Function fSienna { Format-ConsoleColor24 -Color $PSRainbowColors.Sienna -Type Fg }
Function fMaroon { Format-ConsoleColor24 -Color $PSRainbowColors.Maroon -Type Fg }
Function fBrown { Format-ConsoleColor24 -Color $PSRainbowColors.Brown -Type Fg }
Function fWhite { Format-ConsoleColor24 -Color $PSRainbowColors.White -Type Fg }
Function fGainsboro { Format-ConsoleColor24 -Color $PSRainbowColors.Gainsboro -Type Fg }
Function fSnow { Format-ConsoleColor24 -Color $PSRainbowColors.Snow -Type Fg }
Function fLightGray { Format-ConsoleColor24 -Color $PSRainbowColors.LightGray -Type Fg }
Function fHoneydew { Format-ConsoleColor24 -Color $PSRainbowColors.Honeydew -Type Fg }
Function fSilver { Format-ConsoleColor24 -Color $PSRainbowColors.Silver -Type Fg }
Function fMintCream { Format-ConsoleColor24 -Color $PSRainbowColors.MintCream -Type Fg }
Function fDarkGray { Format-ConsoleColor24 -Color $PSRainbowColors.DarkGray -Type Fg }
Function fAzure { Format-ConsoleColor24 -Color $PSRainbowColors.Azure -Type Fg }
Function fGray { Format-ConsoleColor24 -Color $PSRainbowColors.Gray -Type Fg }
Function fAliceBlue { Format-ConsoleColor24 -Color $PSRainbowColors.AliceBlue -Type Fg }
Function fDimGray { Format-ConsoleColor24 -Color $PSRainbowColors.DimGray -Type Fg }
Function fGhostWhite { Format-ConsoleColor24 -Color $PSRainbowColors.GhostWhite -Type Fg }
Function fLightSlateGray { Format-ConsoleColor24 -Color $PSRainbowColors.LightSlateGray -Type Fg }
Function fWhiteSmoke { Format-ConsoleColor24 -Color $PSRainbowColors.WhiteSmoke -Type Fg }
Function fSlateGray { Format-ConsoleColor24 -Color $PSRainbowColors.SlateGray -Type Fg }
Function fSeashell { Format-ConsoleColor24 -Color $PSRainbowColors.Seashell -Type Fg }
Function fDarkSlateGray { Format-ConsoleColor24 -Color $PSRainbowColors.DarkSlateGray -Type Fg }
Function fBeige { Format-ConsoleColor24 -Color $PSRainbowColors.Beige -Type Fg }
Function fBlack { Format-ConsoleColor24 -Color $PSRainbowColors.Black -Type Fg }
Function fOldLace { Format-ConsoleColor24 -Color $PSRainbowColors.OldLace -Type Fg }
Function fFloralWhite { Format-ConsoleColor24 -Color $PSRainbowColors.FloralWhite -Type Fg }
Function fIvory { Format-ConsoleColor24 -Color $PSRainbowColors.Ivory -Type Fg }
Function fAntiqueWhite { Format-ConsoleColor24 -Color $PSRainbowColors.AntiqueWhite -Type Fg }
Function fLinen { Format-ConsoleColor24 -Color $PSRainbowColors.Linen -Type Fg }
Function fLavenderBlush { Format-ConsoleColor24 -Color $PSRainbowColors.LavenderBlush -Type Fg }
Function fMistyRose { Format-ConsoleColor24 -Color $PSRainbowColors.MistyRose -Type Fg }
Function fSystemGray_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray_Light -Type Fg }
Function fSystemGray_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray_Dark -Type Fg }
Function fSystemGray_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray_LightHC -Type Fg }
Function fSystemGray_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray_DarkHC -Type Fg }
Function fSystemGray2_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray2_Light -Type Fg }
Function fSystemGray2_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray2_Dark -Type Fg }
Function fSystemGray2_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray2_LightHC -Type Fg }
Function fSystemGray2_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray2_DarkHC -Type Fg }
Function fSystemGray3_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray3_Light -Type Fg }
Function fSystemGray3_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray3_Dark -Type Fg }
Function fSystemGray3_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray3_LightHC -Type Fg }
Function fSystemGray3_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray3_DarkHC -Type Fg }
Function fSystemGray4_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray4_Light -Type Fg }
Function fSystemGray4_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray4_Dark -Type Fg }
Function fSystemGray4_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray4_LightHC -Type Fg }
Function fSystemGray4_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray4_DarkHC -Type Fg }
Function fSystemGray5_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray5_Light -Type Fg }
Function fSystemGray5_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray5_Dark -Type Fg }
Function fSystemGray5_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray5_LightHC -Type Fg }
Function fSystemGray5_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray5_DarkHC -Type Fg }
Function fSystemGray6_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray6_Light -Type Fg }
Function fSystemGray6_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray6_Dark -Type Fg }
Function fSystemGray6_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray6_LightHC -Type Fg }
Function fSystemGray6_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray6_DarkHC -Type Fg }
Function fSystemRed_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemRed_Light -Type Fg }
Function fSystemRed_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemRed_Dark -Type Fg }
Function fSystemRed_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemRed_LightHC -Type Fg }
Function fSystemRed_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemRed_DarkHC -Type Fg }
Function fSystemOrange_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemOrange_Light -Type Fg }
Function fSystemOrange_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemOrange_Dark -Type Fg }
Function fSystemOrange_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemOrange_LightHC -Type Fg }
Function fSystemOrange_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemOrange_DarkHC -Type Fg }
Function fSystemYellow_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemYellow_Light -Type Fg }
Function fSystemYellow_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemYellow_Dark -Type Fg }
Function fSystemYellow_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemYellow_LightHC -Type Fg }
Function fSystemYellow_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemYellow_DarkHC -Type Fg }
Function fSystemGreen_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGreen_Light -Type Fg }
Function fSystemGreen_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGreen_Dark -Type Fg }
Function fSystemGreen_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGreen_LightHC -Type Fg }
Function fSystemGreen_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGreen_DarkHC -Type Fg }
Function fSystemMint_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemMint_Light -Type Fg }
Function fSystemMint_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemMint_Dark -Type Fg }
Function fSystemMint_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemMint_LightHC -Type Fg }
Function fSystemMint_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemMint_DarkHC -Type Fg }
Function fSystemTeal_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemTeal_Light -Type Fg }
Function fSystemTeal_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemTeal_Dark -Type Fg }
Function fSystemTeal_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemTeal_LightHC -Type Fg }
Function fSystemTeal_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemTeal_DarkHC -Type Fg }
Function fSystemCyan_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemCyan_Light -Type Fg }
Function fSystemCyan_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemCyan_Dark -Type Fg }
Function fSystemCyan_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemCyan_LightHC -Type Fg }
Function fSystemCyan_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemCyan_DarkHC -Type Fg }
Function fSystemBlue_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBlue_Light -Type Fg }
Function fSystemBlue_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBlue_Dark -Type Fg }
Function fSystemBlue_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBlue_LightHC -Type Fg }
Function fSystemBlue_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBlue_DarkHC -Type Fg }
Function fSystemIndigo_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemIndigo_Light -Type Fg }
Function fSystemIndigo_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemIndigo_Dark -Type Fg }
Function fSystemIndigo_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemIndigo_LightHC -Type Fg }
Function fSystemIndigo_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemIndigo_DarkHC -Type Fg }
Function fSystemPurple_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPurple_Light -Type Fg }
Function fSystemPurple_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPurple_Dark -Type Fg }
Function fSystemPurple_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPurple_LightHC -Type Fg }
Function fSystemPurple_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPurple_DarkHC -Type Fg }
Function fSystemPink_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPink_Light -Type Fg }
Function fSystemPink_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPink_Dark -Type Fg }
Function fSystemPink_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPink_LightHC -Type Fg }
Function fSystemPink_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPink_DarkHC -Type Fg }
Function fSystemBrown_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBrown_Light -Type Fg }
Function fSystemBrown_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBrown_Dark -Type Fg }
Function fSystemBrown_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBrown_LightHC -Type Fg }
Function fSystemBrown_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBrown_DarkHC -Type Fg }

# BACKGROUND COLOR FUNCTION SHORTHANDS
Function bIndianRed { Format-ConsoleColor24 -Color $PSRainbowColors.IndianRed -Type Bg }
Function bCrimson { Format-ConsoleColor24 -Color $PSRainbowColors.Crimson -Type Bg }
Function bLightCoral { Format-ConsoleColor24 -Color $PSRainbowColors.LightCoral -Type Bg }
Function bRed { Format-ConsoleColor24 -Color $PSRainbowColors.Red -Type Bg }
Function bSalmon { Format-ConsoleColor24 -Color $PSRainbowColors.Salmon -Type Bg }
Function bFireBrick { Format-ConsoleColor24 -Color $PSRainbowColors.FireBrick -Type Bg }
Function bDarkSalmon { Format-ConsoleColor24 -Color $PSRainbowColors.DarkSalmon -Type Bg }
Function bDarkRed { Format-ConsoleColor24 -Color $PSRainbowColors.DarkRed -Type Bg }
Function bPink { Format-ConsoleColor24 -Color $PSRainbowColors.Pink -Type Bg }
Function bMediumVioletRed { Format-ConsoleColor24 -Color $PSRainbowColors.MediumVioletRed -Type Bg }
Function bLightPink { Format-ConsoleColor24 -Color $PSRainbowColors.LightPink -Type Bg }
Function bPaleVioletRed { Format-ConsoleColor24 -Color $PSRainbowColors.PaleVioletRed -Type Bg }
Function bHotPink { Format-ConsoleColor24 -Color $PSRainbowColors.HotPink -Type Bg }
Function bDeepPink { Format-ConsoleColor24 -Color $PSRainbowColors.DeepPink -Type Bg }
Function bLightSalmon { Format-ConsoleColor24 -Color $PSRainbowColors.LightSalmon -Type Bg }
Function bDarkOrange { Format-ConsoleColor24 -Color $PSRainbowColors.DarkOrange -Type Bg }
Function bCoral { Format-ConsoleColor24 -Color $PSRainbowColors.Coral -Type Bg }
Function bOrange { Format-ConsoleColor24 -Color $PSRainbowColors.Orange -Type Bg }
Function bTomato { Format-ConsoleColor24 -Color $PSRainbowColors.Tomato -Type Bg }
Function bGold { Format-ConsoleColor24 -Color $PSRainbowColors.Gold -Type Bg }
Function bOrangeRed { Format-ConsoleColor24 -Color $PSRainbowColors.OrangeRed -Type Bg }
Function bYellow { Format-ConsoleColor24 -Color $PSRainbowColors.Yellow -Type Bg }
Function bLightYellow { Format-ConsoleColor24 -Color $PSRainbowColors.LightYellow -Type Bg }
Function bPapayaWhip { Format-ConsoleColor24 -Color $PSRainbowColors.PapayaWhip -Type Bg }
Function bLemonChiffon { Format-ConsoleColor24 -Color $PSRainbowColors.LemonChiffon -Type Bg }
Function bMoccasin { Format-ConsoleColor24 -Color $PSRainbowColors.Moccasin -Type Bg }
Function bLightGoldenrodYellow { Format-ConsoleColor24 -Color $PSRainbowColors.LightGoldenrodYellow -Type Bg }
Function bPeachPuff { Format-ConsoleColor24 -Color $PSRainbowColors.PeachPuff -Type Bg }
Function bPaleGoldenrod { Format-ConsoleColor24 -Color $PSRainbowColors.PaleGoldenrod -Type Bg }
Function bKhaki { Format-ConsoleColor24 -Color $PSRainbowColors.Khaki -Type Bg }
Function bDarkKhaki { Format-ConsoleColor24 -Color $PSRainbowColors.DarkKhaki -Type Bg }
Function bLavender { Format-ConsoleColor24 -Color $PSRainbowColors.Lavender -Type Bg }
Function bMediumOrchid { Format-ConsoleColor24 -Color $PSRainbowColors.MediumOrchid -Type Bg }
Function bThistle { Format-ConsoleColor24 -Color $PSRainbowColors.Thistle -Type Bg }
Function bDarkOrchid { Format-ConsoleColor24 -Color $PSRainbowColors.DarkOrchid -Type Bg }
Function bPlum { Format-ConsoleColor24 -Color $PSRainbowColors.Plum -Type Bg }
Function bDarkViolet { Format-ConsoleColor24 -Color $PSRainbowColors.DarkViolet -Type Bg }
Function bViolet { Format-ConsoleColor24 -Color $PSRainbowColors.Violet -Type Bg }
Function bBlueViolet { Format-ConsoleColor24 -Color $PSRainbowColors.BlueViolet -Type Bg }
Function bOrchid { Format-ConsoleColor24 -Color $PSRainbowColors.Orchid -Type Bg }
Function bMediumPurple { Format-ConsoleColor24 -Color $PSRainbowColors.MediumPurple -Type Bg }
Function bMagenta { Format-ConsoleColor24 -Color $PSRainbowColors.Magenta -Type Bg }
Function bFuchsia { Format-ConsoleColor24 -Color $PSRainbowColors.Fuchsia -Type Bg }
Function bSlateBlue { Format-ConsoleColor24 -Color $PSRainbowColors.SlateBlue -Type Bg }
Function bMediumSlateBlue { Format-ConsoleColor24 -Color $PSRainbowColors.MediumSlateBlue -Type Bg }
Function bDarkSlateBlue { Format-ConsoleColor24 -Color $PSRainbowColors.DarkSlateBlue -Type Bg }
Function bPurple { Format-ConsoleColor24 -Color $PSRainbowColors.Purple -Type Bg }
Function bIndigo { Format-ConsoleColor24 -Color $PSRainbowColors.Indigo -Type Bg }
Function bGreenYellow { Format-ConsoleColor24 -Color $PSRainbowColors.GreenYellow -Type Bg }
Function bSeaGreen { Format-ConsoleColor24 -Color $PSRainbowColors.SeaGreen -Type Bg }
Function bChartreuse { Format-ConsoleColor24 -Color $PSRainbowColors.Chartreuse -Type Bg }
Function bForestGreen { Format-ConsoleColor24 -Color $PSRainbowColors.ForestGreen -Type Bg }
Function bLawnGreen { Format-ConsoleColor24 -Color $PSRainbowColors.LawnGreen -Type Bg }
Function bGreen { Format-ConsoleColor24 -Color $PSRainbowColors.Green -Type Bg }
Function bLime { Format-ConsoleColor24 -Color $PSRainbowColors.Lime -Type Bg }
Function bDarkGreen { Format-ConsoleColor24 -Color $PSRainbowColors.DarkGreen -Type Bg }
Function bLimeGreen { Format-ConsoleColor24 -Color $PSRainbowColors.LimeGreen -Type Bg }
Function bYellowGreen { Format-ConsoleColor24 -Color $PSRainbowColors.YellowGreen -Type Bg }
Function bPaleGreen { Format-ConsoleColor24 -Color $PSRainbowColors.PaleGreen -Type Bg }
Function bOliveDrab { Format-ConsoleColor24 -Color $PSRainbowColors.OliveDrab -Type Bg }
Function bLightGreen { Format-ConsoleColor24 -Color $PSRainbowColors.LightGreen -Type Bg }
Function bOlive { Format-ConsoleColor24 -Color $PSRainbowColors.Olive -Type Bg }
Function bMediumSpringGreen { Format-ConsoleColor24 -Color $PSRainbowColors.MediumSpringGreen -Type Bg }
Function bDarkOliveGreen { Format-ConsoleColor24 -Color $PSRainbowColors.DarkOliveGreen -Type Bg }
Function bSpringGreen { Format-ConsoleColor24 -Color $PSRainbowColors.SpringGreen -Type Bg }
Function bMediumAquamarine { Format-ConsoleColor24 -Color $PSRainbowColors.MediumAquamarine -Type Bg }
Function bMediumSeaGreen { Format-ConsoleColor24 -Color $PSRainbowColors.MediumSeaGreen -Type Bg }
Function bDarkSeaGreen { Format-ConsoleColor24 -Color $PSRainbowColors.DarkSeaGreen -Type Bg }
Function bLightSeaGreen { Format-ConsoleColor24 -Color $PSRainbowColors.LightSeaGreen -Type Bg }
Function bDarkCyan { Format-ConsoleColor24 -Color $PSRainbowColors.DarkCyan -Type Bg }
Function bTeal { Format-ConsoleColor24 -Color $PSRainbowColors.Teal -Type Bg }
Function bAqua { Format-ConsoleColor24 -Color $PSRainbowColors.Aqua -Type Bg }
Function bCyan { Format-ConsoleColor24 -Color $PSRainbowColors.Cyan -Type Bg }
Function bSkyBlue { Format-ConsoleColor24 -Color $PSRainbowColors.SkyBlue -Type Bg }
Function bLightCyan { Format-ConsoleColor24 -Color $PSRainbowColors.LightCyan -Type Bg }
Function bLightSkyBlue { Format-ConsoleColor24 -Color $PSRainbowColors.LightSkyBlue -Type Bg }
Function bPaleTurquoise { Format-ConsoleColor24 -Color $PSRainbowColors.PaleTurquoise -Type Bg }
Function bDeepSkyBlue { Format-ConsoleColor24 -Color $PSRainbowColors.DeepSkyBlue -Type Bg }
Function bAquamarine { Format-ConsoleColor24 -Color $PSRainbowColors.Aquamarine -Type Bg }
Function bDodgerBlue { Format-ConsoleColor24 -Color $PSRainbowColors.DodgerBlue -Type Bg }
Function bTurquoise { Format-ConsoleColor24 -Color $PSRainbowColors.Turquoise -Type Bg }
Function bCornflowerBlue { Format-ConsoleColor24 -Color $PSRainbowColors.CornflowerBlue -Type Bg }
Function bMediumTurquoise { Format-ConsoleColor24 -Color $PSRainbowColors.MediumTurquoise -Type Bg }
Function bRoyalBlue { Format-ConsoleColor24 -Color $PSRainbowColors.RoyalBlue -Type Bg }
Function bDarkTurquoise { Format-ConsoleColor24 -Color $PSRainbowColors.DarkTurquoise -Type Bg }
Function bBlue { Format-ConsoleColor24 -Color $PSRainbowColors.Blue -Type Bg }
Function bCadetBlue { Format-ConsoleColor24 -Color $PSRainbowColors.CadetBlue -Type Bg }
Function bMediumBlue { Format-ConsoleColor24 -Color $PSRainbowColors.MediumBlue -Type Bg }
Function bSteelBlue { Format-ConsoleColor24 -Color $PSRainbowColors.SteelBlue -Type Bg }
Function bDarkBlue { Format-ConsoleColor24 -Color $PSRainbowColors.DarkBlue -Type Bg }
Function bLightSteelBlue { Format-ConsoleColor24 -Color $PSRainbowColors.LightSteelBlue -Type Bg }
Function bNavy { Format-ConsoleColor24 -Color $PSRainbowColors.Navy -Type Bg }
Function bPowderBlue { Format-ConsoleColor24 -Color $PSRainbowColors.PowderBlue -Type Bg }
Function bMidnightBlue { Format-ConsoleColor24 -Color $PSRainbowColors.MidnightBlue -Type Bg }
Function bLightBlue { Format-ConsoleColor24 -Color $PSRainbowColors.LightBlue -Type Bg }
Function bCornsilk { Format-ConsoleColor24 -Color $PSRainbowColors.Cornsilk -Type Bg }
Function bRosyBrown { Format-ConsoleColor24 -Color $PSRainbowColors.RosyBrown -Type Bg }
Function bBlanchedAlmond { Format-ConsoleColor24 -Color $PSRainbowColors.BlanchedAlmond -Type Bg }
Function bSandyBrown { Format-ConsoleColor24 -Color $PSRainbowColors.SandyBrown -Type Bg }
Function bBisque { Format-ConsoleColor24 -Color $PSRainbowColors.Bisque -Type Bg }
Function bGoldenrod { Format-ConsoleColor24 -Color $PSRainbowColors.Goldenrod -Type Bg }
Function bNavajoWhite { Format-ConsoleColor24 -Color $PSRainbowColors.NavajoWhite -Type Bg }
Function bDarkGoldenrod { Format-ConsoleColor24 -Color $PSRainbowColors.DarkGoldenrod -Type Bg }
Function bWheat { Format-ConsoleColor24 -Color $PSRainbowColors.Wheat -Type Bg }
Function bPeru { Format-ConsoleColor24 -Color $PSRainbowColors.Peru -Type Bg }
Function bBurlyWood { Format-ConsoleColor24 -Color $PSRainbowColors.BurlyWood -Type Bg }
Function bChocolate { Format-ConsoleColor24 -Color $PSRainbowColors.Chocolate -Type Bg }
Function bTan { Format-ConsoleColor24 -Color $PSRainbowColors.Tan -Type Bg }
Function bSaddleBrown { Format-ConsoleColor24 -Color $PSRainbowColors.SaddleBrown -Type Bg }
Function bSienna { Format-ConsoleColor24 -Color $PSRainbowColors.Sienna -Type Bg }
Function bMaroon { Format-ConsoleColor24 -Color $PSRainbowColors.Maroon -Type Bg }
Function bBrown { Format-ConsoleColor24 -Color $PSRainbowColors.Brown -Type Bg }
Function bWhite { Format-ConsoleColor24 -Color $PSRainbowColors.White -Type Bg }
Function bGainsboro { Format-ConsoleColor24 -Color $PSRainbowColors.Gainsboro -Type Bg }
Function bSnow { Format-ConsoleColor24 -Color $PSRainbowColors.Snow -Type Bg }
Function bLightGray { Format-ConsoleColor24 -Color $PSRainbowColors.LightGray -Type Bg }
Function bHoneydew { Format-ConsoleColor24 -Color $PSRainbowColors.Honeydew -Type Bg }
Function bSilver { Format-ConsoleColor24 -Color $PSRainbowColors.Silver -Type Bg }
Function bMintCream { Format-ConsoleColor24 -Color $PSRainbowColors.MintCream -Type Bg }
Function bDarkGray { Format-ConsoleColor24 -Color $PSRainbowColors.DarkGray -Type Bg }
Function bAzure { Format-ConsoleColor24 -Color $PSRainbowColors.Azure -Type Bg }
Function bGray { Format-ConsoleColor24 -Color $PSRainbowColors.Gray -Type Bg }
Function bAliceBlue { Format-ConsoleColor24 -Color $PSRainbowColors.AliceBlue -Type Bg }
Function bDimGray { Format-ConsoleColor24 -Color $PSRainbowColors.DimGray -Type Bg }
Function bGhostWhite { Format-ConsoleColor24 -Color $PSRainbowColors.GhostWhite -Type Bg }
Function bLightSlateGray { Format-ConsoleColor24 -Color $PSRainbowColors.LightSlateGray -Type Bg }
Function bWhiteSmoke { Format-ConsoleColor24 -Color $PSRainbowColors.WhiteSmoke -Type Bg }
Function bSlateGray { Format-ConsoleColor24 -Color $PSRainbowColors.SlateGray -Type Bg }
Function bSeashell { Format-ConsoleColor24 -Color $PSRainbowColors.Seashell -Type Bg }
Function bDarkSlateGray { Format-ConsoleColor24 -Color $PSRainbowColors.DarkSlateGray -Type Bg }
Function bBeige { Format-ConsoleColor24 -Color $PSRainbowColors.Beige -Type Bg }
Function bBlack { Format-ConsoleColor24 -Color $PSRainbowColors.Black -Type Bg }
Function bOldLace { Format-ConsoleColor24 -Color $PSRainbowColors.OldLace -Type Bg }
Function bFloralWhite { Format-ConsoleColor24 -Color $PSRainbowColors.FloralWhite -Type Bg }
Function bIvory { Format-ConsoleColor24 -Color $PSRainbowColors.Ivory -Type Bg }
Function bAntiqueWhite { Format-ConsoleColor24 -Color $PSRainbowColors.AntiqueWhite -Type Bg }
Function bLinen { Format-ConsoleColor24 -Color $PSRainbowColors.Linen -Type Bg }
Function bLavenderBlush { Format-ConsoleColor24 -Color $PSRainbowColors.LavenderBlush -Type Bg }
Function bMistyRose { Format-ConsoleColor24 -Color $PSRainbowColors.MistyRose -Type Bg }
Function bSystemGray_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray_Light -Type Bg }
Function bSystemGray_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray_Dark -Type Bg }
Function bSystemGray_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray_LightHC -Type Bg }
Function bSystemGray_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray_DarkHC -Type Bg }
Function bSystemGray2_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray2_Light -Type Bg }
Function bSystemGray2_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray2_Dark -Type Bg }
Function bSystemGray2_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray2_LightHC -Type Bg }
Function bSystemGray2_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray2_DarkHC -Type Bg }
Function bSystemGray3_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray3_Light -Type Bg }
Function bSystemGray3_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray3_Dark -Type Bg }
Function bSystemGray3_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray3_LightHC -Type Bg }
Function bSystemGray3_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray3_DarkHC -Type Bg }
Function bSystemGray4_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray4_Light -Type Bg }
Function bSystemGray4_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray4_Dark -Type Bg }
Function bSystemGray4_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray4_LightHC -Type Bg }
Function bSystemGray4_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray4_DarkHC -Type Bg }
Function bSystemGray5_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray5_Light -Type Bg }
Function bSystemGray5_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray5_Dark -Type Bg }
Function bSystemGray5_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray5_LightHC -Type Bg }
Function bSystemGray5_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray5_DarkHC -Type Bg }
Function bSystemGray6_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray6_Light -Type Bg }
Function bSystemGray6_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray6_Dark -Type Bg }
Function bSystemGray6_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray6_LightHC -Type Bg }
Function bSystemGray6_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGray6_DarkHC -Type Bg }
Function bSystemRed_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemRed_Light -Type Bg }
Function bSystemRed_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemRed_Dark -Type Bg }
Function bSystemRed_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemRed_LightHC -Type Bg }
Function bSystemRed_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemRed_DarkHC -Type Bg }
Function bSystemOrange_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemOrange_Light -Type Bg }
Function bSystemOrange_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemOrange_Dark -Type Bg }
Function bSystemOrange_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemOrange_LightHC -Type Bg }
Function bSystemOrange_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemOrange_DarkHC -Type Bg }
Function bSystemYellow_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemYellow_Light -Type Bg }
Function bSystemYellow_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemYellow_Dark -Type Bg }
Function bSystemYellow_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemYellow_LightHC -Type Bg }
Function bSystemYellow_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemYellow_DarkHC -Type Bg }
Function bSystemGreen_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGreen_Light -Type Bg }
Function bSystemGreen_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGreen_Dark -Type Bg }
Function bSystemGreen_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGreen_LightHC -Type Bg }
Function bSystemGreen_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemGreen_DarkHC -Type Bg }
Function bSystemMint_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemMint_Light -Type Bg }
Function bSystemMint_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemMint_Dark -Type Bg }
Function bSystemMint_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemMint_LightHC -Type Bg }
Function bSystemMint_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemMint_DarkHC -Type Bg }
Function bSystemTeal_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemTeal_Light -Type Bg }
Function bSystemTeal_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemTeal_Dark -Type Bg }
Function bSystemTeal_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemTeal_LightHC -Type Bg }
Function bSystemTeal_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemTeal_DarkHC -Type Bg }
Function bSystemCyan_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemCyan_Light -Type Bg }
Function bSystemCyan_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemCyan_Dark -Type Bg }
Function bSystemCyan_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemCyan_LightHC -Type Bg }
Function bSystemCyan_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemCyan_DarkHC -Type Bg }
Function bSystemBlue_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBlue_Light -Type Bg }
Function bSystemBlue_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBlue_Dark -Type Bg }
Function bSystemBlue_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBlue_LightHC -Type Bg }
Function bSystemBlue_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBlue_DarkHC -Type Bg }
Function bSystemIndigo_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemIndigo_Light -Type Bg }
Function bSystemIndigo_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemIndigo_Dark -Type Bg }
Function bSystemIndigo_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemIndigo_LightHC -Type Bg }
Function bSystemIndigo_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemIndigo_DarkHC -Type Bg }
Function bSystemPurple_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPurple_Light -Type Bg }
Function bSystemPurple_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPurple_Dark -Type Bg }
Function bSystemPurple_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPurple_LightHC -Type Bg }
Function bSystemPurple_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPurple_DarkHC -Type Bg }
Function bSystemPink_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPink_Light -Type Bg }
Function bSystemPink_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPink_Dark -Type Bg }
Function bSystemPink_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPink_LightHC -Type Bg }
Function bSystemPink_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemPink_DarkHC -Type Bg }
Function bSystemBrown_Light { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBrown_Light -Type Bg }
Function bSystemBrown_Dark { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBrown_Dark -Type Bg }
Function bSystemBrown_LightHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBrown_LightHC -Type Bg }
Function bSystemBrown_DarkHC { Format-ConsoleColor24 -Color $PSRainbowColors.SystemBrown_DarkHC -Type Bg }

Function AR { "`e[m" }
